### ISSUE TITLE
name resolution in the chroot

### ISSUE THREAD

**Issue by chimay** [mtrkss/arch-compat-tutorial#1]
To access the network in the arch chroot, I had to fill /etc/resolv.conf with the correct address.
Without that, pacman can't access the mirrors.

**Comment by mtrkss** [comment]
yeah forgot about that, sorry. also gonna move adding locales to locale.gen a little earlier since you don't have a text editor at that stage.

**Comment by mtrkss** [comment]
Fixed! Thanks you!
